version: '3'
services:
  webapp:
    image: openresty/openresty:latest
    container_name: webapp
    hostname: webapp
    networks:
    - oauth_network

  openresty:
    image: openresty/openresty:latest
    container_name: openresty
    hostname: openresty
    ports:
    - '${HTTP_PORT}:80'
    env_file:
    - ./.env
    volumes:
    - ./openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
    # - ./openresty/conf.d:/usr/local/openresty/nginx/conf/conf.d
    # - ./openresty/default.d:/usr/local/openresty/nginx/conf/default.d
    networks:
    - oauth_network

  oauth2-proxy:
    container_name: oauth2-proxy
    hostname: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - 4180:4180
    environment:
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_OIDC_EMAIL_CLAIM: sub
      OAUTH2_PROXY_SCOPE: "openid"
      # keycloakで設定したClient IDと同じ
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      # keycloakで取得したCredentials
      OAUTH2_PROXY_CLIENT_SECRET: "taAhCUFAemBr3Q0pnTESj6Y2V0JBi6yo"
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://keycloak:8443/realms/demo_realm
      # OAUTH2_PROXY_COOKIE_SECRETは「python -c 'import os,base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())'」で生成可。
      OAUTH2_PROXY_COOKIE_SECRET: "5JEx-EnDmjnlN-1wd2EQDMrLLEly5NOUUSYsZCiy3Tc="
      # keycloakで設定したRealmの名前
      OAUTH2_PROXY_COOKIE_NAME: "auth_demo"
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
      OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY: "true"
      OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
      # 以下、HTTPS ではなく HTTP で動かすための設定
      OAUTH2_PROXY_REDIRECT_URL: ""
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      # OAUTH2_PROXY_COOKIE_EXPIRE: "12h"
      # OAUTH2_PROXY_COOKIE_SECURE: "true"
      # OAUTH2_PROXY_SET_XAUTHREQUEST: "true"
      # OAUTH2_PROXY_REVERSE_PROXY: "true"
      # OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    networks:
    - oauth_network

  ldap-server:
    image: osixia/openldap:latest
    restart: always
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "my-company.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly_password"
      LDAP_TLS_VERIFY_CLIENT: "never" 
    ports:
      - "389:389"
    volumes:
      - ./openldap/var/lib/ldap:/var/lib/ldap
      - ./openldap/etc/ldap/slapd.d:/etc/ldap/slapd.d
      - ./openldap/testuser.ldif:/slapd/assets/custome/testuser.ldif
    networks:
    - oauth_network

  # ログイン情報
  # Login DN: cn=admin,dc=my-company,dc=com
  # Password: admin
  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    restart: always
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    links:
      - "ldap-server:ldap"
    networks:
    - oauth_network

networks:
  oauth_network:
    external: true